### PR TITLE
Add Wants= and add systemd runtime timeout

### PR DESCRIPTION
**Pull request by jswantek**

### CODE REVIEW

**Review by seanshahkarami — APPROVED** [review]
Looks good to me!

**Review by seanshahkarami — COMMENTED** [review]
Only thing I'd confirm is that terminating from RunTimeMax allows the on-failure policy to work. The docs say the service is "put into a failure state", so it should work... but good to check.

**Comment by jswantek** [comment]
I believe this does what we want.

I modified current waggle-registration service running on my nx with the following changes
- added RuntimeMaxSec=10 to the service file, reloaded the systemctl daemon-reload
- added a time.sleep(60) the main()

```
Feb 27 00:24:10 ws-nxcore systemd[1]: waggle-registration.service: Service hold-off time over, scheduling restart.
Feb 27 00:24:10 ws-nxcore systemd[1]: waggle-registration.service: Scheduled restart job, restart counter is at 10.
Feb 27 00:24:10 ws-nxcore systemd[1]: Started Waggle Registration.
Feb 27 00:24:20 ws-nxcore systemd[1]: waggle-registration.service: Service reached runtime time limit. Stopping.
Feb 27 00:24:20 ws-nxcore systemd[1]: waggle-registration.service: Failed with result 'timeout'.
```

and the systemd status after the failure was

```
● waggle-registration.service - Waggle Registration
   Loaded: loaded (/etc/systemd/system/waggle-registration.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: timeout) since Sat 2021-02-27 00:24:20 UTC; 1min 26s ago
  Process: 10170 ExecStart=/usr/bin/waggle-registration (code=killed, signal=TERM)
 Main PID: 10170 (code=killed, signal=TERM)
```

then after i removed the sleep in the code it all worked again

```
Feb 27 00:27:20 ws-nxcore systemd[1]: waggle-registration.service: Service hold-off time over, scheduling restart.
Feb 27 00:27:20 ws-nxcore systemd[1]: waggle-registration.service: Scheduled restart job, restart counter is at 11.
Feb 27 00:27:20 ws-nxcore systemd[1]: Stopped Waggle Registration.
Feb 27 00:27:20 ws-nxcore systemd[1]: Started Waggle Registration.
Feb 27 00:27:20 ws-nxcore waggle-registration[11569]: 2021-02-27 00:27:20,795  [registration-service:191] (INFO): Generating node-id from network interface [wan0]
Feb 27 00:27:20 ws-nxcore waggle-registration[11569]: 2021-02-27 00:27:20,796  [registration-service:208] (INFO): Getting credentials from beehive for node-id [000048b02d05a0a4].
Feb 27 00:27:20 ws-nxcore waggle-registration[11569]: 2021-02-27 00:27:20,797  [registration-service:218] (INFO): Node already has all credentials. Skipping registration.
```

```
● waggle-registration.service - Waggle Registration
   Loaded: loaded (/etc/systemd/system/waggle-registration.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) since Sat 2021-02-27 00:27:20 UTC; 20s ago
  Process: 11569 ExecStart=/usr/bin/waggle-registration (code=exited, status=0/SUCCESS)
 Main PID: 11569 (code=exited, status=0/SUCCESS)
```

**Comment by jswantek** [comment]
> Only thing I'd confirm is that terminating from RunTimeMax allows the on-failure policy to work. The docs say the service is "put into a failure state", so it should work... but good to check.

I believe this does what we want.

I modified current waggle-registration service running on my nx with the following changes
- added RuntimeMaxSec=10 to the service file, reloaded the systemctl daemon-reload
- added a time.sleep(60) the main()

```
Feb 27 00:24:10 ws-nxcore systemd[1]: waggle-registration.service: Service hold-off time over, scheduling restart.
Feb 27 00:24:10 ws-nxcore systemd[1]: waggle-registration.service: Scheduled restart job, restart counter is at 10.
Feb 27 00:24:10 ws-nxcore systemd[1]: Started Waggle Registration.
Feb 27 00:24:20 ws-nxcore systemd[1]: waggle-registration.service: Service reached runtime time limit. Stopping.
Feb 27 00:24:20 ws-nxcore systemd[1]: waggle-registration.service: Failed with result 'timeout'.
```

and the systemd status after the failure was

```
● waggle-registration.service - Waggle Registration
   Loaded: loaded (/etc/systemd/system/waggle-registration.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: timeout) since Sat 2021-02-27 00:24:20 UTC; 1min 26s ago
  Process: 10170 ExecStart=/usr/bin/waggle-registration (code=killed, signal=TERM)
 Main PID: 10170 (code=killed, signal=TERM)
```

then after i removed the sleep in the code it all worked again

```
Feb 27 00:27:20 ws-nxcore systemd[1]: waggle-registration.service: Service hold-off time over, scheduling restart.
Feb 27 00:27:20 ws-nxcore systemd[1]: waggle-registration.service: Scheduled restart job, restart counter is at 11.
Feb 27 00:27:20 ws-nxcore systemd[1]: Stopped Waggle Registration.
Feb 27 00:27:20 ws-nxcore systemd[1]: Started Waggle Registration.
Feb 27 00:27:20 ws-nxcore waggle-registration[11569]: 2021-02-27 00:27:20,795  [registration-service:191] (INFO): Generating node-id from network interface [wan0]
Feb 27 00:27:20 ws-nxcore waggle-registration[11569]: 2021-02-27 00:27:20,796  [registration-service:208] (INFO): Getting credentials from beehive for node-id [000048b02d05a0a4].
Feb 27 00:27:20 ws-nxcore waggle-registration[11569]: 2021-02-27 00:27:20,797  [registration-service:218] (INFO): Node already has all credentials. Skipping registration.
```

```
● waggle-registration.service - Waggle Registration
   Loaded: loaded (/etc/systemd/system/waggle-registration.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) since Sat 2021-02-27 00:27:20 UTC; 20s ago
  Process: 11569 ExecStart=/usr/bin/waggle-registration (code=exited, status=0/SUCCESS)
 Main PID: 11569 (code=exited, status=0/SUCCESS)
```

**Pull request merged**
